#!/bin/bash
#
# Paul Lam
# CSE 374 Homework 4
# problem 2
# 05/08/2023
#
# Mesaures and outputs the size of the page

if [ $# -ne 1 ]; then
  echo "No arguments provided" >&2
  exit 1
fi

URL="$1"

temp_file=$(mktemp /tmp/measurepage.XXXXXX)


wget -q -O "$temp_file" "$URL"


if [ $? -eq 0 ]; then
  wordcount -w "$temp_file" | awk '{print $1}'
else
  echo 0
fi

rm "$temp_file"

exit 0
